[package]
name = "rush-expand"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rush-parser = { path = "../rush-parser" }
globset = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
