[package]
name = "rush-executor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rush-parser = { path = "../rush-parser" }
rush-expand = { path = "../rush-expand" }
rush-job = { path = "../rush-job" }
rush-interactive = { path = "../rush-interactive" }
nix = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
globset = { workspace = true }
regex = { workspace = true }
