[package]
name = "rush-executor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rush-parser = { path = "../rush-parser" }
rush-expand = { path = "../rush-expand" }
rush-job = { path = "../rush-job" }
nix = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
