[package]
name = "rush-eval"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rush-parser = { path = "../rush-parser" }
rush-expand = { path = "../rush-expand" }
rush-executor = { path = "../rush-executor" }
thiserror = { workspace = true }
anyhow = { workspace = true }
